apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: op-scim-bridge
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "1"
        run.googleapis.com/cpu-throttling: "false"
        run.googleapis.com/startup-cpu-boost: "true"
        run.googleapis.com/container-dependencies: '{"scim":["redis"]}'
    spec:
      containers:
        - name: scim
          image: 1password/scim:v2.9.11
          ports:
            - name: http1
              containerPort: 3002
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
            - name: credentials
              mountPath: /home/opuser/.op
        - name: redis
          image: redis
          args:
            - --maxmemory 256mb
            - --maxmemory-policy volatile-lru
            - --save ""
          startupProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
      volumes:
        - name: credentials
          secret:
            secretName: scimsession
            items:
              - key: latest
                path: scimsession
