apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base

patches:
  - target:
      version: v1
      kind: ConfigMap
      name: op-scim-configmap
    path: patch-configmap.yaml
  - target:
      version: v1
      kind: Service
      name: op-scim-service
    path: patch-service.yaml