services:
  redis:
    image: docker.io/library/redis:latest
    container_name: redis
    command: --maxmemory 256mb --maxmemory-policy volatile-lru --save ""
    networks:
      - op-scim

  scim:
    image: docker.io/1password/scim:${SCIM_IMAGE_VERSION}
    container_name: scim
    ports:
      - "80:3002"
    env_file:
      - ./../scim.env
    networks:
      - op-scim
    depends_on:
      - redis
    secrets:
      - scimsession
      - workspace-credentials
      - workspace-settings

networks:
  op-scim:

secrets:
  scimsession:
    name: scimsession
  workspace-credentials:
    name: workspace-credentials
  workspace-settings:
    name: workspace-settings
