version: "3.3"
services:
  scim:
    secrets:
      - source: op-tls-key
        target: op-tls-key
        uid: "999"
        gid: "999"
        mode: 0440
      - source: op-tls-crt
        target: op-tls-crt
        uid: "999"
        gid: "999"
        mode: 0440
    environment:
      - OP_TLS_KEY_FILE=/run/secrets/op-tls-key
      - OP_TLS_CERT_FILE=/run/secrets/op-tls-crt
secrets:
  op-tls-key:
    external: true
  op-tls-crt:
    external: true
