version: "3.3"
services:
  scim:
   secrets:
      - source: workspace-settings
        target: workspace-settings
        uid: "999"
        gid: "999"
        mode: 0440
      - source: workspace-credentials
        target: workspace-credentials
        uid: "999"
        gid: "999"
        mode: 0440

secrets:
  workspace-settings:
    external: true
  workspace-credentials:
    external: true