name: op-scim-bridge
services:
  - image:
      registry: library
      registry_type: DOCKER_HUB
      repository: redis
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-0.5gb
    internal_ports:
      - 6379
    name: op-scim-redis
    run_command: redis-server --maxmemory 256mb --maxmemory-policy volatile-lru --save ""
  - envs:
      - key: OP_REDIS_URL
        scope: RUN_AND_BUILD_TIME
        value: redis://${op-scim-redis.PRIVATE_DOMAIN}:${op-scim-redis.PRIVATE_PORT}
      - key: OP_SESSION
        scope: RUN_AND_BUILD_TIME
        type: SECRET
        value: op://${VAULT:-op-scim}/${ITEM:-"scimsession file"}/base64_encoded
      - key: OP_WORKSPACE_CREDENTIALS
        scope: RUN_AND_BUILD_TIME
        type: SECRET
        value: op://${VAULT:-op-scim}/${ITEM:-"workspace-credentials"}/base64_encoded_credentials
      - key: OP_WORKSPACE_SETTINGS
        scope: RUN_AND_BUILD_TIME
        type: SECRET
        value: op://${VAULT:-op-scim}/${ITEM:-"workspace-credentials"}/base64_encoded_settings
    health_check:
      http_path: /ping
    http_port: 3002
    image:
      registry: 1password
      registry_type: DOCKER_HUB
      repository: scim
      tag: v2.9.13
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-0.5gb
    name: op-scim-bridge
    routes:
      - path: /
