version: '3.3'

services:
    scim:
        build: .
        ports: 
            - "80:8080"
            - "443:8443"
        links:
            - redis
        entrypoint: ["/op-scim/op-scim", "--letsencrypt-domain=op-scim-demo.com"]
    redis:
        image: redis:latest
