apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- op-scim-config.yaml
- op-scim-deployment.yaml
- op-scim-service.yaml
- redis-config.yaml
- redis-deployment.yaml
- redis-service.yaml
secretGenerator:
- files:
  - scimsession
  name: scimsession