apiVersion: v1
kind: Service
metadata:
  name: op-scim
  labels:
    app: op-scim
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    name: tls
    port: 443
    targetPort: 8443
  - protocol: TCP
    name: http
    port: 80
    targetPort: 8080
  selector:
    app: op-scim