apiVersion: v1
kind: Service
metadata:
  name: op-scim-service
  labels:
    app: op-scim
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 443
    targetPort: 3002
  selector:
    app: op-scim