apiVersion: v1
kind: Service
metadata:
  name: op-scim
  labels:
    app: op-scim
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    name: https
    port: 443
    targetPort: 8443
# Traffic on :80 is needed to perform the LetsEncrypt certificate challenges, 
# after which all SCIM traffic will be served on :443.
  - protocol: TCP
    name: http
    port: 80
    targetPort: 8080
  selector:
    app: op-scim
