apiVersion: v1
kind: ConfigMap
metadata:
  name: op-redis-configmap
data:
  redis.conf: |
    # Configure Redis as cache

    # Cache memory limit
    maxmemory 256mb

    # Evict only expired keys when memory limit is reached using least recently used algorithm
    maxmemory-policy volatile-lru

    # Disable snapshotting
    save ""
