apiVersion: apps/v1
kind: Deployment
metadata:
  name: op-scim-redis
spec:
  selector:
    matchLabels:
      app: op-scim-redis
  replicas: 1
  template:
    metadata:
      labels:
        app: op-scim-redis
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
        runAsGroup: 999
        fsGroup: 999
      containers:
        - name: op-scim-redis
          image: redis
          ports:
            - containerPort: 6379
              name: redis
          args:
            - --maxmemory 256mb
            - --maxmemory-policy volatile-lru
            - --save ""
          resources:
            requests:
              cpu: 125m
              memory: 512M
            limits:
              memory: 512M
