apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base

patches:
  - target:
      version: v1
      kind: Deployment
      name: op-scim-bridge
    path: patch-deployment.yaml
  - target:
      version: v1
      kind: ConfigMap
      name: op-scim-configmap
    path: patch-configmap.yaml

secretGenerator:
  - files:
      - workspace-credentials.json
    name: workspace-credentials
  - files:
      - workspace-settings.json
    name: workspace-settings