version: "2.2"
services:
  scim:
    image: 1password/scim:v2.9.5
    ports:
      - "3002:3002"
      - "80:8080"
      - "443:8443"
    networks:
      - op-scim
    env_file: scim.env
    restart: always
  redis:
    image: redis:latest
    networks:
      - op-scim
    env_file: redis.env
    restart: always

networks:
  op-scim:
