version: "2.2"
services:
  scim:
    image: 1password/scim:v1.6.2
    ports:
      - "80:8080"
      - "443:8443"
    networks:
      - op-scim
    env_file: scim.env
    restart: always
  redis:
    image: redis:latest
    expose:
      - "6379"
    networks:
      - op-scim
    restart: always

networks:
  op-scim:
