version: "3.3"
services:
  scim:
    image: 1password/scim:v2.9.9
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    networks:
      - op-scim
    ports:
      #- "80:8080"
      - "443:8443"
      #- "3002:3002"
    secrets:
      - source: scimsession
        target: scimsession
        uid: "999"
        gid: "999"
        mode: 0440
      ## Uncomment this section for DNS01 secret
      # - source: dns01-config
      #   target: dns01-config
      #   uid: "999"
      #   gid: "999"
      #   mode: 0440
    env_file: scim.env
    depends_on: ["redis"]
  redis:
    image: redis:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    networks:
      - op-scim
    env_file: redis.env

networks:
  op-scim:

secrets:
  scimsession:
    external: true
