services:
  scim:
    secrets:
      - source: workspace-credentials
        target: /home/opuser/.op/workspace-credentials.json
        uid: "999"
        gid: "999"
        mode: 0440
      - source: workspace-settings
        target: /home/opuser/.op/workspace-settings.json
        uid: "999"
        gid: "999"
        mode: 0440
secrets:
  workspace-credentials:
    name: workspace-credentials
    file: ./workspace-credentials.json
  workspace-settings:
    name: workspace-settings
    file: ./workspace-settings.json
