#cloud-config
users:
     - name: user_name
       gecos: Operator
       sudo: ALL=(ALL) NOPASSWD:ALL
       shell: /bin/bash
       ssh-authorized-keys: 
           - ssh-rsa key user_name@example.com

