apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: op-scim

resources:
- ../../base
- ingress.yaml

configMapGenerator:
  - name: op-scim-configmap
    behavior: merge
    literals:
      - OP_PING_SERVER="1"
      # Set this to the FQDN you've selected for your SCIM Bridge deployment
      - OP_LETSENCRYPT_DOMAIN=""
      # - OP_TLS_KEY_FILE="/tls/tls.key"
      # - OP_TLS_CERT_FILE="/tls/tls.crt"
      # (optional) uncomment this line to change the email that is used when Let's Encrypt issues your SCIM bridge a certificate
      # default: "1pw@[OP_LETSENCRYPT_DOMAIN]"
      # - OP_LETSENCRYPT_EMAIL=""

secretGenerator:
  - name: scimsession
    behavior: replace
    files:
    - scimsession
